---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
- name: Ensure 'man' directory exists.
  ansible.builtin.file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install Required Ubuntu Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-11-jdk
    - apt-transport-https

- name: Import the signing key for the Neo Technology Debian repository for Neo4j
  ansible.builtin.apt_key:
    url: https://debian.neo4j.org/neotechnology.gpg.key
    state: present

- name: Add the Neo Technology Debian repository for Neo4j
  ansible.builtin.apt_repository:
    repo: "{{ neo4j_debian_repo }}"
    state: present
    update_cache: true
