---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
- name: Ensure 'man' directory exists.
  ansible.builtin.file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
    mode: '0644'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Required Ubuntu Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ neo4j_java }}"
    - apt-transport-https
    - gpg-agent
    - python3-debian

- name: Ensure conflicting java packages are not present
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ neo4j_java_remove }}"

- name: Add Neo4j apt repository
  ansible.builtin.deb822_repository:
    name: "{% if neo4j_version is defined %}{{ neo4j_version.split('.')[0] }}{% else %}latest{% endif %}"
    types: deb
    uris: "https://debian.neo4j.com/"
    suites: stable
    components:
      - main
    signed_by: https://debian.neo4j.com/neotechnology.gpg.key
  notify:
    - Update apt cache

- name: Determine the neo4j package to install
  ansible.builtin.set_fact:
    neo4j_package: neo4j{% if neo4j_edition == 'enterprise' %}-enterprise{% endif %}{% if neo4j_version is defined %}=1:{{ neo4j_version }}{% endif %}

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
