---
# handlers file for neo4j

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart Neo4j
  ansible.builtin.service:
    name: neo4j
    state: restarted
  become: true
  become_method: ansible.builtin.sudo
  when:
    - not is_container|bool
