---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 7474/tcp
      - 7687/tcp
    published_ports:
      - 0.0.0.0:7474:7474/tcp
      - 0.0.0.0:7687:7687/tcp
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
